#!/usr/bin/python
# -*- coding: latin-1 -*-
import os, sys

def ayudaPrincipal():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMOS CRIPTOGRAFICOS                                                     |"
	print "|										      |"
	print "| sintaxis: python principal.py <algoritmo>					      |"
	print "|										      |"
	print "| <algoritmo>:									      |"
	print "|\t-sc    Algoritmo de sustitución monoalfabética Julio Cesar		      |"
	print "|\t-sa    Algoritmo de sustitución monoalfabética afin			      |"
	print "|\t-sva   Algoritmo de sustitución polialfabética Vigenere Autoclave	      |"
	print "|\t-mr   Algoritmo de transposicion Mascara Rotativa	                      |"
	print "|\t-caf   Algoritmo de criptoanálisis por Frecuencia	                      |"
	print "|										      |"
	print "| consultar ayuda de un algoritmo en específico: 				      |"
	print "|                                   sintaxis: python principal.py <algoritmo>	      |"
	print "|										      |"
	print "|										      |"
	print "| Ayudas Sobre el alfabeto:  			    				      |"
	print "|\tsintaxis: python principal.py Alfabeto <tipoAyuda>	       		      |"
	print "|										      |"
	print "| <tipoAyuda>:									      |"
	print "|\t-m    Mostrar alfabeto		     				              |"
	print "|\t-a <simbolo>    agregar	simbolo al alfabeto    			              |"
	print "|\t-t    Tamaño del alfabeto	      					      |"
	print "|										      |"
	print "| Elaborado por:  Jonathan Ibarra						      |"
	print "|                 Tania Cañizares						      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaVigenere():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO VIGENERE AUTOCLAVE                                                  |"
	print "|										      |"
	print "| sintaxis: python principal.py -sva <modo> <archivoEntrada> <Archivoclave>           |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| <Archivoclave>: El archivo que contiene la clave para cifrar o descifrar el mensaje |"	
	print "|										      |"
	print "| NOTA: El archivo de salida tendra el mismo nombre que el archivo de entrada 	      |"	
	print "|	agregando al final la extencion '.cif'(cifrar) o '.dec'(descifrar)            |"	
	print "|	ej: quijote.txt.cif o quijote.txt.dec      				      |"	
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sva -c quijote.txt Archivo_Clave.txt             |"
	print "|\tdescifrar: python principal.py -sva -d quijote.txt.cif Archivo_Clave.txt      |"
	print "|										      |"
	print "| Elaborado por:  Jonathan Ibarra y Tania Cañizares	      			      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaCesar():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO CESAR		                                                      |"
	print "|										      |"
	print "| sintaxis: python principal.py -sc <modo> <archivoEntrada> <clave>                   |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| <clave>: es un numero que corresponde al desplazamiento del alfabeto                |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sc -c quijote.txt 4                              |"
	print "|\tdescifrar: python principal.py -sc -d quijote.txt.cif 4                       |"
	print "|										      |"
	print "| Elaborado por:  Tania Cañizares y Jonathan Ibarra				      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaAfin():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                                     |"
	print "| \tALGORITMO AFIN		                                                      |"
	print "|										      |"
	print "| sintaxis: python principal.py -sa <modo> <archivoEntrada> <a> <b>                   |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| a y b deben estar en el siguiente rango 0<(a,b)<n-1  con n= Tamano del alfabeto     |"
	print "|										      |"
	print "| <a>: es un numero que sea co-primo con n (mcd(a,n)=1)      n=Tamano del alfabeto    |"
	print "|										      |"
	print "| <b>: es un numero que corresponde al desplazamiento del alfabeto(clave)             |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -sa -c quijote.txt 15 4                           |"
	print "|\tdescifrar: python principal.py -sa -d quijote.txt.cif 15 4                        |"
	print "|										      |"
	print "| Elaborado por:  Tania Cañizares y Jonathan Ibarra				      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"

def ayudaFrecuencia():
	print " -----------------------------------------------------------------------------------------"
	print "|                                                                                         |"
	print "| \tCRIPTOANÁLISIS POR FRECUENCIA		                                          |"
	print "|										          |"
	print "| sintaxis: python principal.py -caf <archivoCifrado>                                     |"
	print "|			  				 		 	          |"
	print "| <archivoCifrado>: Nombre del archivo de entrada que desea descifrar ej: quijote.txt.cif |"
	print "|										          |"
	print "| Ejemplo:    					 				          |"
	print "|\tpython principal.py -caf quijote.txt.cif                                          |"
	print "|										          |"
	print "| Elaborado por:  Tania Cañizares y Jonathan Ibarra				          |"
	print "|         									          |"
	print " -----------------------------------------------------------------------------------------"

def ayudaMascara():
	print " --------------------------------------------------------------------------------------"
	print "|                                                                             	      |"
	print "| \tALGORITMO MASCARA ROTATIVA	                                              |"
	print "|										      |"
	print "| sintaxis: python principal.py -mr <modo> <archivoEntrada> <Mascara>                 |"
	print "|										      |"
	print "| <modo>:									      |"
	print "|\t-c    para cifrar el archivo			             		      |"
	print "|\t-d    para decifrar el archivo                  			      |"
	print "| 										      |"
	print "| <archivoEntrada>: Nombre del archivo de entrada a cifrar o descifrar ej: quijote.txt|"
	print "|										      |"
	print "| <Mascara>: Corresponde a la Clave. Revisar la documentacion 			      |"
	print "|										      |"
	print "| Ejemplos:    					 				      |"
	print "|\tcifrar: python principal.py -mr -c quijote.txt mascara.txt                    |"
	print "|\tdescifrar: python principal.py -mr -d quijote.txt.cif mascara.txt             |"
	print "|										      |"
	print "| Elaborado por:  Tania Cañizares y Jonathan Ibarra				      |"
	print "|         									      |"
	print " --------------------------------------------------------------------------------------"
